// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/talondb.proto

package talondbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MutationEventKind mirrors talon-language's factstore.EventKind so the
// adapter can map straight across.
type MutationEventKind int32

const (
	MutationEventKind_MUTATION_EVENT_KIND_UNSPECIFIED MutationEventKind = 0
	MutationEventKind_MUTATION_EVENT_KIND_ASSERT      MutationEventKind = 1 // doc newly written (no prior version)
	MutationEventKind_MUTATION_EVENT_KIND_CHANGE      MutationEventKind = 2 // doc bytes changed; old_doc carries prior content
	MutationEventKind_MUTATION_EVENT_KIND_RETRACT     MutationEventKind = 3 // doc deleted; old_doc carries prior content
)

// Enum value maps for MutationEventKind.
var (
	MutationEventKind_name = map[int32]string{
		0: "MUTATION_EVENT_KIND_UNSPECIFIED",
		1: "MUTATION_EVENT_KIND_ASSERT",
		2: "MUTATION_EVENT_KIND_CHANGE",
		3: "MUTATION_EVENT_KIND_RETRACT",
	}
	MutationEventKind_value = map[string]int32{
		"MUTATION_EVENT_KIND_UNSPECIFIED": 0,
		"MUTATION_EVENT_KIND_ASSERT":      1,
		"MUTATION_EVENT_KIND_CHANGE":      2,
		"MUTATION_EVENT_KIND_RETRACT":     3,
	}
)

func (x MutationEventKind) Enum() *MutationEventKind {
	p := new(MutationEventKind)
	*p = x
	return p
}

func (x MutationEventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_talondb_proto_enumTypes[0].Descriptor()
}

func (MutationEventKind) Type() protoreflect.EnumType {
	return &file_proto_talondb_proto_enumTypes[0]
}

func (x MutationEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutationEventKind.Descriptor instead.
func (MutationEventKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{0}
}

// DocIDList is the canonical bag-of-doc-ids return shape. Clients are
// free to sort/dedupe locally; the server makes no ordering promise.
type DocIDList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocIds        []string               `protobuf:"bytes,1,rep,name=doc_ids,json=docIds,proto3" json:"doc_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocIDList) Reset() {
	*x = DocIDList{}
	mi := &file_proto_talondb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocIDList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocIDList) ProtoMessage() {}

func (x *DocIDList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocIDList.ProtoReflect.Descriptor instead.
func (*DocIDList) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{0}
}

func (x *DocIDList) GetDocIds() []string {
	if x != nil {
		return x.DocIds
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_proto_talondb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{1}
}

func (x *StringList) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Doc           []byte                 `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_talondb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *PutRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *PutRequest) GetDoc() []byte {
	if x != nil {
		return x.Doc
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_talondb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *GetRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doc           []byte                 `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_talondb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetDoc() []byte {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_talondb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *DeleteRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type BatchPutEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Doc           []byte                 `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPutEntry) Reset() {
	*x = BatchPutEntry{}
	mi := &file_proto_talondb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutEntry) ProtoMessage() {}

func (x *BatchPutEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutEntry.ProtoReflect.Descriptor instead.
func (*BatchPutEntry) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{6}
}

func (x *BatchPutEntry) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *BatchPutEntry) GetDoc() []byte {
	if x != nil {
		return x.Doc
	}
	return nil
}

type BatchPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Entries       []*BatchPutEntry       `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPutRequest) Reset() {
	*x = BatchPutRequest{}
	mi := &file_proto_talondb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutRequest) ProtoMessage() {}

func (x *BatchPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutRequest.ProtoReflect.Descriptor instead.
func (*BatchPutRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{7}
}

func (x *BatchPutRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *BatchPutRequest) GetEntries() []*BatchPutEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Term          string                 `protobuf:"bytes,2,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_proto_talondb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{8}
}

func (x *LookupRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *LookupRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

type LookupPrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupPrefixRequest) Reset() {
	*x = LookupPrefixRequest{}
	mi := &file_proto_talondb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupPrefixRequest) ProtoMessage() {}

func (x *LookupPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupPrefixRequest.ProtoReflect.Descriptor instead.
func (*LookupPrefixRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{9}
}

func (x *LookupPrefixRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *LookupPrefixRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type NumericRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Attr          string                 `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
	Min           float64                `protobuf:"fixed64,3,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,4,opt,name=max,proto3" json:"max,omitempty"`
	MinExclusive  bool                   `protobuf:"varint,5,opt,name=min_exclusive,json=minExclusive,proto3" json:"min_exclusive,omitempty"`
	MaxExclusive  bool                   `protobuf:"varint,6,opt,name=max_exclusive,json=maxExclusive,proto3" json:"max_exclusive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericRangeRequest) Reset() {
	*x = NumericRangeRequest{}
	mi := &file_proto_talondb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericRangeRequest) ProtoMessage() {}

func (x *NumericRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericRangeRequest.ProtoReflect.Descriptor instead.
func (*NumericRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{10}
}

func (x *NumericRangeRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *NumericRangeRequest) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

func (x *NumericRangeRequest) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *NumericRangeRequest) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *NumericRangeRequest) GetMinExclusive() bool {
	if x != nil {
		return x.MinExclusive
	}
	return false
}

func (x *NumericRangeRequest) GetMaxExclusive() bool {
	if x != nil {
		return x.MaxExclusive
	}
	return false
}

type WindowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Types         []string               `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`
	WindowNanos   int64                  `protobuf:"varint,4,opt,name=window_nanos,json=windowNanos,proto3" json:"window_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowRequest) Reset() {
	*x = WindowRequest{}
	mi := &file_proto_talondb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowRequest) ProtoMessage() {}

func (x *WindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowRequest.ProtoReflect.Descriptor instead.
func (*WindowRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{11}
}

func (x *WindowRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *WindowRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *WindowRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *WindowRequest) GetWindowNanos() int64 {
	if x != nil {
		return x.WindowNanos
	}
	return 0
}

type TemporalEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	AtUnixNanos   int64                  `protobuf:"varint,3,opt,name=at_unix_nanos,json=atUnixNanos,proto3" json:"at_unix_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporalEvent) Reset() {
	*x = TemporalEvent{}
	mi := &file_proto_talondb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalEvent) ProtoMessage() {}

func (x *TemporalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalEvent.ProtoReflect.Descriptor instead.
func (*TemporalEvent) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{12}
}

func (x *TemporalEvent) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *TemporalEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TemporalEvent) GetAtUnixNanos() int64 {
	if x != nil {
		return x.AtUnixNanos
	}
	return 0
}

type WindowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TemporalEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowResponse) Reset() {
	*x = WindowResponse{}
	mi := &file_proto_talondb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowResponse) ProtoMessage() {}

func (x *WindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowResponse.ProtoReflect.Descriptor instead.
func (*WindowResponse) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{13}
}

func (x *WindowResponse) GetEvents() []*TemporalEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type GroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Attr          string                 `protobuf:"bytes,3,opt,name=attr,proto3" json:"attr,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRequest) Reset() {
	*x = GroupRequest{}
	mi := &file_proto_talondb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRequest) ProtoMessage() {}

func (x *GroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRequest.ProtoReflect.Descriptor instead.
func (*GroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{14}
}

func (x *GroupRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *GroupRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GroupRequest) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

func (x *GroupRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GroupResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Count          int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	FirstUnixNanos int64                  `protobuf:"varint,2,opt,name=first_unix_nanos,json=firstUnixNanos,proto3" json:"first_unix_nanos,omitempty"`
	LastUnixNanos  int64                  `protobuf:"varint,3,opt,name=last_unix_nanos,json=lastUnixNanos,proto3" json:"last_unix_nanos,omitempty"`
	DocIds         []string               `protobuf:"bytes,4,rep,name=doc_ids,json=docIds,proto3" json:"doc_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GroupResponse) Reset() {
	*x = GroupResponse{}
	mi := &file_proto_talondb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupResponse) ProtoMessage() {}

func (x *GroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupResponse.ProtoReflect.Descriptor instead.
func (*GroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{15}
}

func (x *GroupResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GroupResponse) GetFirstUnixNanos() int64 {
	if x != nil {
		return x.FirstUnixNanos
	}
	return 0
}

func (x *GroupResponse) GetLastUnixNanos() int64 {
	if x != nil {
		return x.LastUnixNanos
	}
	return 0
}

func (x *GroupResponse) GetDocIds() []string {
	if x != nil {
		return x.DocIds
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Attr          string                 `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_talondb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{16}
}

func (x *StatsRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *StatsRequest) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Mean          float64                `protobuf:"fixed64,2,opt,name=mean,proto3" json:"mean,omitempty"`
	M2            float64                `protobuf:"fixed64,3,opt,name=m2,proto3" json:"m2,omitempty"`
	Min           float64                `protobuf:"fixed64,4,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,5,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_talondb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{17}
}

func (x *StatsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StatsResponse) GetMean() float64 {
	if x != nil {
		return x.Mean
	}
	return 0
}

func (x *StatsResponse) GetM2() float64 {
	if x != nil {
		return x.M2
	}
	return 0
}

func (x *StatsResponse) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *StatsResponse) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type LastSeenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	RecordType    string                 `protobuf:"bytes,3,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastSeenRequest) Reset() {
	*x = LastSeenRequest{}
	mi := &file_proto_talondb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastSeenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastSeenRequest) ProtoMessage() {}

func (x *LastSeenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastSeenRequest.ProtoReflect.Descriptor instead.
func (*LastSeenRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{18}
}

func (x *LastSeenRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *LastSeenRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *LastSeenRequest) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

type LastSeenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AtUnixNanos   int64                  `protobuf:"varint,1,opt,name=at_unix_nanos,json=atUnixNanos,proto3" json:"at_unix_nanos,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastSeenResponse) Reset() {
	*x = LastSeenResponse{}
	mi := &file_proto_talondb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastSeenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastSeenResponse) ProtoMessage() {}

func (x *LastSeenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastSeenResponse.ProtoReflect.Descriptor instead.
func (*LastSeenResponse) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{19}
}

func (x *LastSeenResponse) GetAtUnixNanos() int64 {
	if x != nil {
		return x.AtUnixNanos
	}
	return 0
}

func (x *LastSeenResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type AncestorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AncestorsRequest) Reset() {
	*x = AncestorsRequest{}
	mi := &file_proto_talondb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AncestorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AncestorsRequest) ProtoMessage() {}

func (x *AncestorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AncestorsRequest.ProtoReflect.Descriptor instead.
func (*AncestorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{20}
}

func (x *AncestorsRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AncestorsRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type DescendantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	RootId        string                 `protobuf:"bytes,2,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescendantsRequest) Reset() {
	*x = DescendantsRequest{}
	mi := &file_proto_talondb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescendantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescendantsRequest) ProtoMessage() {}

func (x *DescendantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescendantsRequest.ProtoReflect.Descriptor instead.
func (*DescendantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{21}
}

func (x *DescendantsRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *DescendantsRequest) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_talondb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{22}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entity_id, when non-empty, restricts the stream to one tenant.
	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	// doc_id_prefix, when non-empty, restricts the stream to docs whose
	// ID starts with this prefix. Combined with entity_id as AND.
	DocIdPrefix   string `protobuf:"bytes,2,opt,name=doc_id_prefix,json=docIdPrefix,proto3" json:"doc_id_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_talondb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{23}
}

func (x *SubscribeRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *SubscribeRequest) GetDocIdPrefix() string {
	if x != nil {
		return x.DocIdPrefix
	}
	return ""
}

type MutationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          MutationEventKind      `protobuf:"varint,1,opt,name=kind,proto3,enum=opentalon.talondb.v1.MutationEventKind" json:"kind,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	DocId         string                 `protobuf:"bytes,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	OldDoc        []byte                 `protobuf:"bytes,4,opt,name=old_doc,json=oldDoc,proto3" json:"old_doc,omitempty"` // empty on Assert; present on Change / Retract
	NewDoc        []byte                 `protobuf:"bytes,5,opt,name=new_doc,json=newDoc,proto3" json:"new_doc,omitempty"` // empty on Retract; present on Assert / Change
	AtUnixNanos   int64                  `protobuf:"varint,6,opt,name=at_unix_nanos,json=atUnixNanos,proto3" json:"at_unix_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationEvent) Reset() {
	*x = MutationEvent{}
	mi := &file_proto_talondb_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationEvent) ProtoMessage() {}

func (x *MutationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationEvent.ProtoReflect.Descriptor instead.
func (*MutationEvent) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{24}
}

func (x *MutationEvent) GetKind() MutationEventKind {
	if x != nil {
		return x.Kind
	}
	return MutationEventKind_MUTATION_EVENT_KIND_UNSPECIFIED
}

func (x *MutationEvent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *MutationEvent) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *MutationEvent) GetOldDoc() []byte {
	if x != nil {
		return x.OldDoc
	}
	return nil
}

func (x *MutationEvent) GetNewDoc() []byte {
	if x != nil {
		return x.NewDoc
	}
	return nil
}

func (x *MutationEvent) GetAtUnixNanos() int64 {
	if x != nil {
		return x.AtUnixNanos
	}
	return 0
}

type ClusterQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Types         []string               `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`                                 // empty = all types
	WindowNanos   int64                  `protobuf:"varint,4,opt,name=window_nanos,json=windowNanos,proto3" json:"window_nanos,omitempty"` // 0 = no upper bound (one cluster per run)
	MinSize       int32                  `protobuf:"varint,5,opt,name=min_size,json=minSize,proto3" json:"min_size,omitempty"`             // ≥1 (1 yields every event as a singleton)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterQueryRequest) Reset() {
	*x = ClusterQueryRequest{}
	mi := &file_proto_talondb_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterQueryRequest) ProtoMessage() {}

func (x *ClusterQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterQueryRequest.ProtoReflect.Descriptor instead.
func (*ClusterQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{25}
}

func (x *ClusterQueryRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ClusterQueryRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ClusterQueryRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ClusterQueryRequest) GetWindowNanos() int64 {
	if x != nil {
		return x.WindowNanos
	}
	return 0
}

func (x *ClusterQueryRequest) GetMinSize() int32 {
	if x != nil {
		return x.MinSize
	}
	return 0
}

type ClusterQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*TemporalCluster     `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterQueryResponse) Reset() {
	*x = ClusterQueryResponse{}
	mi := &file_proto_talondb_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterQueryResponse) ProtoMessage() {}

func (x *ClusterQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterQueryResponse.ProtoReflect.Descriptor instead.
func (*ClusterQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{26}
}

func (x *ClusterQueryResponse) GetClusters() []*TemporalCluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type TemporalCluster struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FirstUnixNanos int64                  `protobuf:"varint,1,opt,name=first_unix_nanos,json=firstUnixNanos,proto3" json:"first_unix_nanos,omitempty"`
	LastUnixNanos  int64                  `protobuf:"varint,2,opt,name=last_unix_nanos,json=lastUnixNanos,proto3" json:"last_unix_nanos,omitempty"`
	Events         []*TemporalEvent       `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TemporalCluster) Reset() {
	*x = TemporalCluster{}
	mi := &file_proto_talondb_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalCluster) ProtoMessage() {}

func (x *TemporalCluster) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talondb_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalCluster.ProtoReflect.Descriptor instead.
func (*TemporalCluster) Descriptor() ([]byte, []int) {
	return file_proto_talondb_proto_rawDescGZIP(), []int{27}
}

func (x *TemporalCluster) GetFirstUnixNanos() int64 {
	if x != nil {
		return x.FirstUnixNanos
	}
	return 0
}

func (x *TemporalCluster) GetLastUnixNanos() int64 {
	if x != nil {
		return x.LastUnixNanos
	}
	return 0
}

func (x *TemporalCluster) GetEvents() []*TemporalEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_proto_talondb_proto protoreflect.FileDescriptor

const file_proto_talondb_proto_rawDesc = "" +
	"\n" +
	"\x13proto/talondb.proto\x12\x14opentalon.talondb.v1\x1a\x1bgoogle/protobuf/empty.proto\"$\n" +
	"\tDocIDList\x12\x17\n" +
	"\adoc_ids\x18\x01 \x03(\tR\x06docIds\"\"\n" +
	"\n" +
	"StringList\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\"R\n" +
	"\n" +
	"PutRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x10\n" +
	"\x03doc\x18\x03 \x01(\fR\x03doc\"@\n" +
	"\n" +
	"GetRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\"5\n" +
	"\vGetResponse\x12\x10\n" +
	"\x03doc\x18\x01 \x01(\fR\x03doc\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"C\n" +
	"\rDeleteRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\"8\n" +
	"\rBatchPutEntry\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x10\n" +
	"\x03doc\x18\x02 \x01(\fR\x03doc\"m\n" +
	"\x0fBatchPutRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12=\n" +
	"\aentries\x18\x02 \x03(\v2#.opentalon.talondb.v1.BatchPutEntryR\aentries\"@\n" +
	"\rLookupRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\tR\x04term\"J\n" +
	"\x13LookupPrefixRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\"\xb4\x01\n" +
	"\x13NumericRangeRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x12\n" +
	"\x04attr\x18\x02 \x01(\tR\x04attr\x12\x10\n" +
	"\x03min\x18\x03 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x01R\x03max\x12#\n" +
	"\rmin_exclusive\x18\x05 \x01(\bR\fminExclusive\x12#\n" +
	"\rmax_exclusive\x18\x06 \x01(\bR\fmaxExclusive\"~\n" +
	"\rWindowRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05types\x18\x03 \x03(\tR\x05types\x12!\n" +
	"\fwindow_nanos\x18\x04 \x01(\x03R\vwindowNanos\"^\n" +
	"\rTemporalEvent\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\"\n" +
	"\rat_unix_nanos\x18\x03 \x01(\x03R\vatUnixNanos\"M\n" +
	"\x0eWindowResponse\x12;\n" +
	"\x06events\x18\x01 \x03(\v2#.opentalon.talondb.v1.TemporalEventR\x06events\"n\n" +
	"\fGroupRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04attr\x18\x03 \x01(\tR\x04attr\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\x90\x01\n" +
	"\rGroupResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12(\n" +
	"\x10first_unix_nanos\x18\x02 \x01(\x03R\x0efirstUnixNanos\x12&\n" +
	"\x0flast_unix_nanos\x18\x03 \x01(\x03R\rlastUnixNanos\x12\x17\n" +
	"\adoc_ids\x18\x04 \x03(\tR\x06docIds\"?\n" +
	"\fStatsRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x12\n" +
	"\x04attr\x18\x02 \x01(\tR\x04attr\"m\n" +
	"\rStatsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x12\n" +
	"\x04mean\x18\x02 \x01(\x01R\x04mean\x12\x0e\n" +
	"\x02m2\x18\x03 \x01(\x01R\x02m2\x12\x10\n" +
	"\x03min\x18\x04 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x05 \x01(\x01R\x03max\"h\n" +
	"\x0fLastSeenRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1f\n" +
	"\vrecord_type\x18\x03 \x01(\tR\n" +
	"recordType\"L\n" +
	"\x10LastSeenResponse\x12\"\n" +
	"\rat_unix_nanos\x18\x01 \x01(\x03R\vatUnixNanos\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"P\n" +
	"\x10AncestorsRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\"J\n" +
	"\x12DescendantsRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x17\n" +
	"\aroot_id\x18\x02 \x01(\tR\x06rootId\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"S\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\"\n" +
	"\rdoc_id_prefix\x18\x02 \x01(\tR\vdocIdPrefix\"\xd6\x01\n" +
	"\rMutationEvent\x12;\n" +
	"\x04kind\x18\x01 \x01(\x0e2'.opentalon.talondb.v1.MutationEventKindR\x04kind\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x15\n" +
	"\x06doc_id\x18\x03 \x01(\tR\x05docId\x12\x17\n" +
	"\aold_doc\x18\x04 \x01(\fR\x06oldDoc\x12\x17\n" +
	"\anew_doc\x18\x05 \x01(\fR\x06newDoc\x12\"\n" +
	"\rat_unix_nanos\x18\x06 \x01(\x03R\vatUnixNanos\"\x9f\x01\n" +
	"\x13ClusterQueryRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05types\x18\x03 \x03(\tR\x05types\x12!\n" +
	"\fwindow_nanos\x18\x04 \x01(\x03R\vwindowNanos\x12\x19\n" +
	"\bmin_size\x18\x05 \x01(\x05R\aminSize\"Y\n" +
	"\x14ClusterQueryResponse\x12A\n" +
	"\bclusters\x18\x01 \x03(\v2%.opentalon.talondb.v1.TemporalClusterR\bclusters\"\xa0\x01\n" +
	"\x0fTemporalCluster\x12(\n" +
	"\x10first_unix_nanos\x18\x01 \x01(\x03R\x0efirstUnixNanos\x12&\n" +
	"\x0flast_unix_nanos\x18\x02 \x01(\x03R\rlastUnixNanos\x12;\n" +
	"\x06events\x18\x03 \x03(\v2#.opentalon.talondb.v1.TemporalEventR\x06events*\x99\x01\n" +
	"\x11MutationEventKind\x12#\n" +
	"\x1fMUTATION_EVENT_KIND_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aMUTATION_EVENT_KIND_ASSERT\x10\x01\x12\x1e\n" +
	"\x1aMUTATION_EVENT_KIND_CHANGE\x10\x02\x12\x1f\n" +
	"\x1bMUTATION_EVENT_KIND_RETRACT\x10\x032\xd7\n" +
	"\n" +
	"\x0eTalonDBService\x12?\n" +
	"\x03Put\x12 .opentalon.talondb.v1.PutRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x03Get\x12 .opentalon.talondb.v1.GetRequest\x1a!.opentalon.talondb.v1.GetResponse\x12E\n" +
	"\x06Delete\x12#.opentalon.talondb.v1.DeleteRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\bBatchPut\x12%.opentalon.talondb.v1.BatchPutRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\x06Lookup\x12#.opentalon.talondb.v1.LookupRequest\x1a\x1f.opentalon.talondb.v1.DocIDList\x12Z\n" +
	"\fLookupPrefix\x12).opentalon.talondb.v1.LookupPrefixRequest\x1a\x1f.opentalon.talondb.v1.DocIDList\x12`\n" +
	"\x12LookupNumericRange\x12).opentalon.talondb.v1.NumericRangeRequest\x1a\x1f.opentalon.talondb.v1.DocIDList\x12X\n" +
	"\vWindowQuery\x12#.opentalon.talondb.v1.WindowRequest\x1a$.opentalon.talondb.v1.WindowResponse\x12U\n" +
	"\n" +
	"GroupCount\x12\".opentalon.talondb.v1.GroupRequest\x1a#.opentalon.talondb.v1.GroupResponse\x12P\n" +
	"\x05Stats\x12\".opentalon.talondb.v1.StatsRequest\x1a#.opentalon.talondb.v1.StatsResponse\x12Y\n" +
	"\bLastSeen\x12%.opentalon.talondb.v1.LastSeenRequest\x1a&.opentalon.talondb.v1.LastSeenResponse\x12U\n" +
	"\tAncestors\x12&.opentalon.talondb.v1.AncestorsRequest\x1a .opentalon.talondb.v1.StringList\x12X\n" +
	"\vDescendants\x12(.opentalon.talondb.v1.DescendantsRequest\x1a\x1f.opentalon.talondb.v1.DocIDList\x12e\n" +
	"\fClusterQuery\x12).opentalon.talondb.v1.ClusterQueryRequest\x1a*.opentalon.talondb.v1.ClusterQueryResponse\x12Z\n" +
	"\tSubscribe\x12&.opentalon.talondb.v1.SubscribeRequest\x1a#.opentalon.talondb.v1.MutationEvent0\x01\x12F\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a$.opentalon.talondb.v1.HealthResponseB/Z-github.com/opentalon/talon-db/proto/talondbpbb\x06proto3"

var (
	file_proto_talondb_proto_rawDescOnce sync.Once
	file_proto_talondb_proto_rawDescData []byte
)

func file_proto_talondb_proto_rawDescGZIP() []byte {
	file_proto_talondb_proto_rawDescOnce.Do(func() {
		file_proto_talondb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_talondb_proto_rawDesc), len(file_proto_talondb_proto_rawDesc)))
	})
	return file_proto_talondb_proto_rawDescData
}

var file_proto_talondb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_talondb_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_talondb_proto_goTypes = []any{
	(MutationEventKind)(0),       // 0: opentalon.talondb.v1.MutationEventKind
	(*DocIDList)(nil),            // 1: opentalon.talondb.v1.DocIDList
	(*StringList)(nil),           // 2: opentalon.talondb.v1.StringList
	(*PutRequest)(nil),           // 3: opentalon.talondb.v1.PutRequest
	(*GetRequest)(nil),           // 4: opentalon.talondb.v1.GetRequest
	(*GetResponse)(nil),          // 5: opentalon.talondb.v1.GetResponse
	(*DeleteRequest)(nil),        // 6: opentalon.talondb.v1.DeleteRequest
	(*BatchPutEntry)(nil),        // 7: opentalon.talondb.v1.BatchPutEntry
	(*BatchPutRequest)(nil),      // 8: opentalon.talondb.v1.BatchPutRequest
	(*LookupRequest)(nil),        // 9: opentalon.talondb.v1.LookupRequest
	(*LookupPrefixRequest)(nil),  // 10: opentalon.talondb.v1.LookupPrefixRequest
	(*NumericRangeRequest)(nil),  // 11: opentalon.talondb.v1.NumericRangeRequest
	(*WindowRequest)(nil),        // 12: opentalon.talondb.v1.WindowRequest
	(*TemporalEvent)(nil),        // 13: opentalon.talondb.v1.TemporalEvent
	(*WindowResponse)(nil),       // 14: opentalon.talondb.v1.WindowResponse
	(*GroupRequest)(nil),         // 15: opentalon.talondb.v1.GroupRequest
	(*GroupResponse)(nil),        // 16: opentalon.talondb.v1.GroupResponse
	(*StatsRequest)(nil),         // 17: opentalon.talondb.v1.StatsRequest
	(*StatsResponse)(nil),        // 18: opentalon.talondb.v1.StatsResponse
	(*LastSeenRequest)(nil),      // 19: opentalon.talondb.v1.LastSeenRequest
	(*LastSeenResponse)(nil),     // 20: opentalon.talondb.v1.LastSeenResponse
	(*AncestorsRequest)(nil),     // 21: opentalon.talondb.v1.AncestorsRequest
	(*DescendantsRequest)(nil),   // 22: opentalon.talondb.v1.DescendantsRequest
	(*HealthResponse)(nil),       // 23: opentalon.talondb.v1.HealthResponse
	(*SubscribeRequest)(nil),     // 24: opentalon.talondb.v1.SubscribeRequest
	(*MutationEvent)(nil),        // 25: opentalon.talondb.v1.MutationEvent
	(*ClusterQueryRequest)(nil),  // 26: opentalon.talondb.v1.ClusterQueryRequest
	(*ClusterQueryResponse)(nil), // 27: opentalon.talondb.v1.ClusterQueryResponse
	(*TemporalCluster)(nil),      // 28: opentalon.talondb.v1.TemporalCluster
	(*emptypb.Empty)(nil),        // 29: google.protobuf.Empty
}
var file_proto_talondb_proto_depIdxs = []int32{
	7,  // 0: opentalon.talondb.v1.BatchPutRequest.entries:type_name -> opentalon.talondb.v1.BatchPutEntry
	13, // 1: opentalon.talondb.v1.WindowResponse.events:type_name -> opentalon.talondb.v1.TemporalEvent
	0,  // 2: opentalon.talondb.v1.MutationEvent.kind:type_name -> opentalon.talondb.v1.MutationEventKind
	28, // 3: opentalon.talondb.v1.ClusterQueryResponse.clusters:type_name -> opentalon.talondb.v1.TemporalCluster
	13, // 4: opentalon.talondb.v1.TemporalCluster.events:type_name -> opentalon.talondb.v1.TemporalEvent
	3,  // 5: opentalon.talondb.v1.TalonDBService.Put:input_type -> opentalon.talondb.v1.PutRequest
	4,  // 6: opentalon.talondb.v1.TalonDBService.Get:input_type -> opentalon.talondb.v1.GetRequest
	6,  // 7: opentalon.talondb.v1.TalonDBService.Delete:input_type -> opentalon.talondb.v1.DeleteRequest
	8,  // 8: opentalon.talondb.v1.TalonDBService.BatchPut:input_type -> opentalon.talondb.v1.BatchPutRequest
	9,  // 9: opentalon.talondb.v1.TalonDBService.Lookup:input_type -> opentalon.talondb.v1.LookupRequest
	10, // 10: opentalon.talondb.v1.TalonDBService.LookupPrefix:input_type -> opentalon.talondb.v1.LookupPrefixRequest
	11, // 11: opentalon.talondb.v1.TalonDBService.LookupNumericRange:input_type -> opentalon.talondb.v1.NumericRangeRequest
	12, // 12: opentalon.talondb.v1.TalonDBService.WindowQuery:input_type -> opentalon.talondb.v1.WindowRequest
	15, // 13: opentalon.talondb.v1.TalonDBService.GroupCount:input_type -> opentalon.talondb.v1.GroupRequest
	17, // 14: opentalon.talondb.v1.TalonDBService.Stats:input_type -> opentalon.talondb.v1.StatsRequest
	19, // 15: opentalon.talondb.v1.TalonDBService.LastSeen:input_type -> opentalon.talondb.v1.LastSeenRequest
	21, // 16: opentalon.talondb.v1.TalonDBService.Ancestors:input_type -> opentalon.talondb.v1.AncestorsRequest
	22, // 17: opentalon.talondb.v1.TalonDBService.Descendants:input_type -> opentalon.talondb.v1.DescendantsRequest
	26, // 18: opentalon.talondb.v1.TalonDBService.ClusterQuery:input_type -> opentalon.talondb.v1.ClusterQueryRequest
	24, // 19: opentalon.talondb.v1.TalonDBService.Subscribe:input_type -> opentalon.talondb.v1.SubscribeRequest
	29, // 20: opentalon.talondb.v1.TalonDBService.Health:input_type -> google.protobuf.Empty
	29, // 21: opentalon.talondb.v1.TalonDBService.Put:output_type -> google.protobuf.Empty
	5,  // 22: opentalon.talondb.v1.TalonDBService.Get:output_type -> opentalon.talondb.v1.GetResponse
	29, // 23: opentalon.talondb.v1.TalonDBService.Delete:output_type -> google.protobuf.Empty
	29, // 24: opentalon.talondb.v1.TalonDBService.BatchPut:output_type -> google.protobuf.Empty
	1,  // 25: opentalon.talondb.v1.TalonDBService.Lookup:output_type -> opentalon.talondb.v1.DocIDList
	1,  // 26: opentalon.talondb.v1.TalonDBService.LookupPrefix:output_type -> opentalon.talondb.v1.DocIDList
	1,  // 27: opentalon.talondb.v1.TalonDBService.LookupNumericRange:output_type -> opentalon.talondb.v1.DocIDList
	14, // 28: opentalon.talondb.v1.TalonDBService.WindowQuery:output_type -> opentalon.talondb.v1.WindowResponse
	16, // 29: opentalon.talondb.v1.TalonDBService.GroupCount:output_type -> opentalon.talondb.v1.GroupResponse
	18, // 30: opentalon.talondb.v1.TalonDBService.Stats:output_type -> opentalon.talondb.v1.StatsResponse
	20, // 31: opentalon.talondb.v1.TalonDBService.LastSeen:output_type -> opentalon.talondb.v1.LastSeenResponse
	2,  // 32: opentalon.talondb.v1.TalonDBService.Ancestors:output_type -> opentalon.talondb.v1.StringList
	1,  // 33: opentalon.talondb.v1.TalonDBService.Descendants:output_type -> opentalon.talondb.v1.DocIDList
	27, // 34: opentalon.talondb.v1.TalonDBService.ClusterQuery:output_type -> opentalon.talondb.v1.ClusterQueryResponse
	25, // 35: opentalon.talondb.v1.TalonDBService.Subscribe:output_type -> opentalon.talondb.v1.MutationEvent
	23, // 36: opentalon.talondb.v1.TalonDBService.Health:output_type -> opentalon.talondb.v1.HealthResponse
	21, // [21:37] is the sub-list for method output_type
	5,  // [5:21] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_talondb_proto_init() }
func file_proto_talondb_proto_init() {
	if File_proto_talondb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_talondb_proto_rawDesc), len(file_proto_talondb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_talondb_proto_goTypes,
		DependencyIndexes: file_proto_talondb_proto_depIdxs,
		EnumInfos:         file_proto_talondb_proto_enumTypes,
		MessageInfos:      file_proto_talondb_proto_msgTypes,
	}.Build()
	File_proto_talondb_proto = out.File
	file_proto_talondb_proto_goTypes = nil
	file_proto_talondb_proto_depIdxs = nil
}
